#!/bin/sh
# Enable eglfs backend
export QT_QPA_PLATFORM=eglfs
# Use the KMS/DRM backend.
export QT_QPA_EGLFS_INTEGRATION=eglfs_kms
# Touchscreen support, see info using utility evtest
export QT_QPA_EVDEV_TOUCHSCREEN_PARAMETERS=/dev/input/event13
# Keyboard support, see info using utility evtest
export QT_QPA_EVDEV_KEYBOARD_PARAMETERS=/dev/input/event3:grab=1
# Disable libinput support for eglfs
export QT_QPA_EGLFS_NO_LIBINPUT=1
# attempt to disable the terminal keyboard on application startup by setting the tty's keyboard mode to K_OFF
export QT_QPA_ENABLE_TERMINAL_KEYBOARD=0
# Enable eglfs debug logging
export QT_QPA_EGLFS_DEBUG=1
# debug input logging
export QT_LOGGING_RULES=qt.qpa.input=true


# turn off tty1 cursor blinking
#setterm -cursor off > /dev/tty1
./build/FBrowser
# clear framebuffer
#cat /dev/zero >/dev/fb0
# back on tt1 cursor blinking
#setterm -cursor on > /dev/tty1
